name: OpenSearch

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  opensearch_tests:
    runs-on: ubuntu-latest
    services:
      es:
        image: opensearchproject/opensearch:2
        ports:
          - 9200:9200
        options: >-
          --env discovery.type=single-node
          --env DISABLE_SECURITY_PLUGIN=true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Opensearch
        run: |
          sleep 10
          curl -s http://localhost:9200

      - name: Run tests
        run: python3 search_test.py --count=2000 --search_db_url=http://localhost:9200
